# Pandas Exercise

In [3]:
from sklearn.impute import SimpleImputer
import pandas as pd

In [4]:
covid_csv  = pd.read_csv("/kaggle/input/covid-19-data/covid_19_data.csv")

In [5]:
covid_csv.head(10) ## shows the top n from the dataset

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0

In [6]:
covid_csv.shape

(306429, 8)

In [7]:
print(covid_csv.columns)
print(covid_csv.dtypes)

Index(['SNo', 'ObservationDate', 'Province/State', 'Country/Region',
       'Last Update', 'Confirmed', 'Deaths', 'Recovered'],
      dtype='object')
SNo                  int64
ObservationDate     object
Province/State      object
Country/Region      object
Last Update         object
Confirmed          float64
Deaths             float64
Recovered          float64
dtype: object

In [8]:
print(covid_csv.isna().any()) ## check if there are any NaN fields in each column

print()

print(covid_csv.isna().sum()) ## gets the sum for NaN from the columns

SNo                False
ObservationDate    False
Province/State      True
Country/Region     False
Last Update        False
Confirmed          False
Deaths             False
Recovered          False
dtype: bool

SNo                    0
ObservationDate        0
Province/State     78103
Country/Region         0
Last Update            0
Confirmed              0
Deaths                 0
Recovered              0
dtype: int64

In [9]:
print(covid_csv["Deaths"].count())

print(covid_csv["Deaths"].mean())

print(covid_csv["Deaths"].max())

print(covid_csv["Deaths"].min())

print() 

## .quantile() manual approach
# percentage = 0.25
# sorted_deaths = covid_csv["Deaths"].sort_values().reset_index(drop=True)
# below_index = covid_csv["Deaths"].count() * percentage
# lower = sorted_deaths[round(below_index)]
# upper = sorted_deaths[round(below_index) + 1]
# calculating = lower + percentage * (upper - lower)
# print(calculating)

#.quantile(percentage) --> tells the number that n% of the data is below
print(covid_csv["Deaths"].quantile(0.25)) 

print(covid_csv['Deaths'].quantile(0.5))

print(covid_csv["Deaths"].quantile(0.75))

print()

## .std() manual approach
# mean = covid_csv["Deaths"].mean()
# sqr_differences = (covid_csv["Deaths"] - mean) ** 2
# variance = sqr_differences.mean()
# std = variance ** 0.5

## shows the average distance that data points are from the mean [standard deviation]
print(covid_csv["Deaths"].std())


## Can just use .describe()
print(covid_csv.describe())

## It's good to do these for all numeric fields

306429
2036.4032679674574
112385.0
-178.0

13.0
192.0
1322.0

6410.938047706185
                 SNo     Confirmed         Deaths     Recovered
count  306429.000000  3.064290e+05  306429.000000  3.064290e+05
mean   153215.000000  8.567091e+04    2036.403268  5.042029e+04
std     88458.577156  2.775516e+05    6410.938048  2.015124e+05
min         1.000000 -3.028440e+05    -178.000000 -8.544050e+05
25%     76608.000000  1.042000e+03      13.000000  1.100000e+01
50%    153215.000000  1.037500e+04     192.000000  1.751000e+03
75%    229822.000000  5.075200e+04    1322.000000  2.027000e+04
max    306429.000000  5.863138e+06  112385.000000  6.399531e+06

#### *Use sort_values() not sort() for Series*

##### *Use reset_index(drop=True) when you want to create a new sequential index, and delete the old index. Without drop=True, it leaves the old index as a column, it just creates a new one*

In [10]:
covid_csv.drop(["SNo", "Last Update"], axis=1, inplace=True) ## inplace=True this changes the original dataframe
print(covid_csv.columns)

Index(['ObservationDate', 'Province/State', 'Country/Region', 'Confirmed',
       'Deaths', 'Recovered'],
      dtype='object')

In [11]:
## can rename columns and indexes with this
covid_csv.rename(columns={"ObservationDate": "Date", "Province/State": "State", "Country/Region": "Country"}, inplace=True)
covid_csv.columns

Index(['Date', 'State', 'Country', 'Confirmed', 'Deaths', 'Recovered'], dtype='object')

In [12]:
covid_csv["Date"] = pd.to_datetime(covid_csv["Date"]) ## convert to datetime. Can give it format
print(covid_csv.dtypes)
print(covid_csv.head(5))

Date         datetime64[ns]
State                object
Country              object
Confirmed           float64
Deaths              float64
Recovered           float64
dtype: object
        Date      State         Country  Confirmed  Deaths  Recovered
0 2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1 2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2 2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3 2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4 2020-01-22      Gansu  Mainland China        0.0     0.0        0.0

In [13]:
simpleImputer = SimpleImputer(strategy="constant", fill_value="California")


df2 = covid_csv.copy()
df2Imputed = pd.DataFrame(simpleImputer.fit_transform(df2), columns=df2.columns)


print(covid_csv.isna().any())

print() 

# print(df2Imputed)
print(df2Imputed.isnull().any())

Date         False
State         True
Country      False
Confirmed    False
Deaths       False
Recovered    False
dtype: bool

Date         False
State        False
Country      False
Confirmed    False
Deaths       False
Recovered    False
dtype: bool

In [14]:
covid_csv.groupby(["Date", "Country"])[["Confirmed", "Deaths", "Recovered"]].sum().reset_index().head(20)

         Date         Country  Confirmed  Deaths  Recovered
0  2020-01-22           China        0.0     0.0        0.0
1  2020-01-22       Hong Kong        0.0     0.0        0.0
2  2020-01-22           Japan        2.0     0.0        0.0
3  2020-01-22        Kiribati        0.0     0.0        0.0
4  2020-01-22           Macau        1.0     0.0        0.0
5  2020-01-22  Mainland China      547.0    17.0       28.0
6  2020-01-22     South Korea        1.0     0.0        0.0
7  2020-01-22          Taiwan        1.0     0.0        0.0
8  2020-01-22        Thailand        4.0     0.0        2.0
9  2020-01-22              US        1.0     0.0        0.0
10 2020-01-23       Australia        0.0     0.0        0.0
11 2020-01-23          Brazil        0.0     0.0        0.0
12 2020-01-23           China        0.0     0.0        0.0
13 2020-01-23        Colombia        0.0     0.0        0.0
14 2020-01-23       Hong Kong        2.0     0.0        0.0
15 2020-01-23           Japan        1.0     0.0        0.0
16 2020-01-23        Kiribati        0.0     0.0        0.0
17 2020-01-23           Macau        2.0     0.0        0.0
18 2020-01-23  Mainland China     1082.0    34.0       58.0
19 2020-01-23        Malaysia        0.0     0.0        0.0

In [15]:
groupedBy = covid_csv.groupby(["Country", "Date"])[["Confirmed", "Deaths", "Recovered"]].sum().reset_index()
groupedBy.sort_values(["Date", "Country"]).head(20)

              Country       Date  Confirmed  Deaths  Recovered
16249           China 2020-01-22        0.0     0.0        0.0
33808       Hong Kong 2020-01-22        0.0     0.0        0.0
39375           Japan 2020-01-22        2.0     0.0        0.0
41216        Kiribati 2020-01-22        0.0     0.0        0.0
47443           Macau 2020-01-22        1.0     0.0        0.0
48373  Mainland China 2020-01-22      547.0    17.0       28.0
72969     South Korea 2020-01-22        1.0     0.0        0.0
77121          Taiwan 2020-01-22        1.0     0.0        0.0
78450        Thailand 2020-01-22        4.0     0.0        2.0
81663              US 2020-01-22        1.0     0.0        0.0
3618        Australia 2020-01-23        0.0     0.0        0.0
10393          Brazil 2020-01-23        0.0     0.0        0.0
16250           China 2020-01-23        0.0     0.0        0.0
16297        Colombia 2020-01-23        0.0     0.0        0.0
33809       Hong Kong 2020-01-23        2.0     0.0        0.0
39376           Japan 2020-01-23        1.0     0.0        0.0
41217        Kiribati 2020-01-23        0.0     0.0        0.0
47444           Macau 2020-01-23        2.0     0.0        0.0
48374  Mainland China 2020-01-23     1082.0    34.0       58.0
49290        Malaysia 2020-01-23        0.0     0.0        0.0

In [16]:
last_date = covid_csv["Date"].max()

only_to_date = covid_csv[covid_csv["Date"]==last_date].sort_values("Confirmed", ascending=False).head(10)

only_to_date

             Date        State    Country  Confirmed    Deaths  Recovered
306127 2021-05-29  Maharashtra      India  5713215.0   94030.0  5339838.0
305718 2021-05-29          NaN     France  5600353.0  108532.0   331686.0
305824 2021-05-29          NaN     Turkey  5235978.0   47271.0  5094279.0
305972 2021-05-29      England         UK  3910803.0  112385.0        0.0
305913 2021-05-29   California         US  3788713.0   63236.0        0.0
305670 2021-05-29          NaN  Argentina  3732263.0   77108.0  3288467.0
306292 2021-05-29    Sao Paulo     Brazil  3254893.0  111123.0  2895697.0
306337 2021-05-29        Texas         US  2952861.0   51491.0        0.0
305735 2021-05-29          NaN       Iran  2893218.0   79741.0  2425033.0
305787 2021-05-29          NaN     Poland  2871371.0   73682.0  2636675.0

In [17]:
latests_date = covid_csv["Date"].max()

only_to_date = covid_csv[covid_csv["Date"]==latests_date]

print(only_to_date["Confirmed"].sum())
print(only_to_date["Deaths"].sum())
print(only_to_date["Recovered"].sum())

169951560.0
3533619.0
107140669.0

In [18]:
covid_csv_cop = covid_csv.copy()

covid_csv_cop["Recovery"] = covid_csv_cop["Recovered"]/covid_csv_cop["Confirmed"] * 100

covid_csv_cop['Recovery'] = covid_csv_cop["Recovery"].fillna(0)

covid_csv_cop["Recovery"]

0          0.000000
1          0.000000
2          0.000000
3          0.000000
4          0.000000
            ...
306424    92.837170
306425     0.000000
306426    97.067449
306427    95.705311
306428     0.000000
Name: Recovery, Length: 306429, dtype: float64

In [19]:
print(covid_csv_cop[covid_csv_cop["Recovery"] > 80].tail(5))

             Date               State         Country  Confirmed  Deaths  \
306421 2021-05-29    Zabaykalsky Krai          Russia    43126.0   669.0
306423 2021-05-29  Zakarpattia Oblast         Ukraine    61611.0  1586.0
306424 2021-05-29   Zaporizhia Oblast         Ukraine   102641.0  2335.0
306426 2021-05-29            Zhejiang  Mainland China     1364.0     1.0
306427 2021-05-29     Zhytomyr Oblast         Ukraine    87550.0  1738.0

        Recovered   Recovery
306421    41650.0  96.577471
306423    58882.0  95.570596
306424    95289.0  92.837170
306426     1324.0  97.067449
306427    83790.0  95.705311

In [20]:
print(covid_csv["Confirmed"][covid_csv["Confirmed"]<0].count())
print(covid_csv["Deaths"][covid_csv["Deaths"]<0].count())
print(covid_csv["Recovered"][covid_csv["Recovered"]<0].count())

print(covid_csv[covid_csv["Deaths"] > covid_csv["Confirmed"]]["Country"].unique())

print(covid_csv["Date"].min())
print(covid_csv["Date"].max())

print(len(covid_csv["Country"].unique()))

1
2
3
['Sudan' 'Canada' 'Chile' 'UK' 'Colombia' 'Belgium']
2020-01-22 00:00:00
2021-05-29 00:00:00
229

In [21]:
covid_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       306429 non-null  datetime64[ns]
 1   State      228326 non-null  object
 2   Country    306429 non-null  object
 3   Confirmed  306429 non-null  float64
 4   Deaths     306429 non-null  float64
 5   Recovered  306429 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 14.0+ MB